---
- name: Distribute compiled binaries across all PROD Nodes
  hosts: prod
  vars_files:
    - ../../vars.yml
    - ../../nodes.yml
  gather_facts: True
  tasks:
  # Distribute!
  - name: Move compiled binary to Remote Machine GOPATH dir
    copy: src={{ ProjectPath }}/PRFLR_{{inventory_hostname}} dest=/root/go/PRFLR/PRFLR_{{inventory_hostname}} mode=0744

  - name: Deliver monit script
    template: src={{ ProjectPath }}/ansible/templates/monit/PRFLR_prod.j2 dest=/etc/monit/conf.d/PRFLR_prod mode=0644

  - name: Stop monit
    service: name=monit state=stopped

  - name: Kill previous process (if any)
    shell: kill -9 $(ps -ef|grep "PRFLR_{{inventory_hostname}}"|grep -v "grep"|awk '{print $2}') || true

  - name: Start monit
    service: name=monit state=started

  - name: Move assets dir to Remote Machine GOPATH assets dir
    synchronize: src={{ ProjectPath }}/assets/ dest=/root/go/PRFLR/assets/
